### ISSUE TITLE
Name Change v2.0

### ISSUE THREAD

**Issue by josephworks** [GlowstonePlusPlus/Bukkit2Sponge#15]
It should be sponge2bukkit if it is an implementation of SpongeAPI for Bukkit servers (Glowstone, Spigot)
cause it is being implemented into bukkit, not sponge
I recommend you call it:
# SpongeBukkit
or drain

**Comment by mastercoms** [comment]
It is converting Bukkit servers to Sponge. But it is a working title, and we will probably change it later on, if we ever get this going again. It's likely we will replace it with some sort of more generic system for loading API systems to be compatible with Glowstone, but that will take huge engineering efforts that I don't think we are ready to do in a timely manner.

**Comment by mastercoms** [comment]
Closing in favor of #6.
